// scripts/seed-products-extended.ts
// Расширенный seed-скрипт для продуктов на основе полного списка средств

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Маппинг брендов
const BRANDS = [
  { name: 'Galderma', country: 'Switzerland' },
  { name: 'La Roche-Posay', country: 'France' },
  { name: 'Akrikhin', country: 'Russia' },
  { name: 'Bioderma', country: 'France' },
  { name: 'Avene', country: 'France' },
  { name: 'Vichy', country: 'France' },
  { name: 'Eucerin', country: 'Germany' },
  { name: 'Topicrem', country: 'France' },
  { name: 'Noreva', country: 'France' },
  { name: 'Dermedic', country: 'Poland' },
  { name: 'Institut Esthederm', country: 'France' },
  { name: 'SkinCeuticals', country: 'USA' },
  { name: 'Cytolife', country: 'France' },
  { name: 'EltaMD', country: 'USA' },
  { name: 'Natura Siberica', country: 'Russia' },
  { name: 'Glytone', country: 'USA' },
  { name: 'Biologique Recherche', country: 'France' },
  { name: 'G.Love', country: 'Russia' },
  { name: 'SUPERBANKA', country: 'Russia' },
  { name: 'Generic', country: 'Various' },
  { name: 'PREMIUM', country: 'Russia' },
  { name: 'AADRE', country: 'Russia' },
  { name: 'Russian', country: 'Russia' }, // Общий бренд для российских средств
] as const;

// Продукты по категориям проблем
const PRODUCTS = [
  // АКНЕ
  {
    name: 'Базирон АС гель 2.5%',
    brand: 'Galderma',
    category: 'cleanser',
    step: 'treatment',
    skinTypes: ['oily', 'combo'],
    concerns: ['acne'],
    ingredients: ['бензоилпероксид'],
    price: 800,
    priceSegment: 'mid',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Гель с бензоилпероксидом для лечения акне',
    marketLinks: { apteka_ru: 'https://apteka.ru', ozon: 'https://ozon.ru' },
  },
  {
    name: 'Дифферин гель',
    brand: 'Galderma',
    category: 'serum',
    step: 'treatment',
    skinTypes: ['oily'],
    concerns: ['acne'],
    ingredients: ['адапален'],
    price: 1200,
    priceSegment: 'mid',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Гель с адапаленом для лечения акне',
    marketLinks: { rigla: 'https://rigla.ru' },
  },
  {
    name: 'Клиндовит гель',
    brand: 'Akrikhin',
    category: 'serum',
    step: 'treatment',
    skinTypes: ['sensitive'],
    concerns: ['acne'],
    ingredients: ['клиндамицин'],
    price: 600,
    priceSegment: 'mid',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Антибактериальный гель с клиндамицином',
    marketLinks: { zdravcity: 'https://zdravcity.ru' },
  },
  {
    name: 'Azelik крем',
    brand: 'Akrikhin',
    category: 'cream',
    step: 'treatment',
    skinTypes: ['oily', 'sensitive'],
    concerns: ['acne', 'pores'],
    ingredients: ['азелаиновая кислота'],
    price: 900,
    priceSegment: 'mid',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Крем с азелаиновой кислотой для лечения акне и постакне',
    marketLinks: { ozon: 'https://ozon.ru' },
  },
  {
    name: 'Effaclar Duo(+) крем-гель',
    brand: 'La Roche-Posay',
    category: 'cream',
    step: 'moisturizer',
    skinTypes: ['combo', 'oily'],
    concerns: ['acne', 'pores'],
    ingredients: ['ниацинамид', 'LHA'],
    price: 1500,
    priceSegment: 'mid',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Крем-гель для проблемной кожи с ниацинамидом',
    marketLinks: { wildberries: 'https://wildberries.ru' },
  },
  {
    name: 'Регецин гель',
    brand: 'Russian',
    category: 'serum',
    step: 'treatment',
    skinTypes: ['dry', 'normal', 'combo', 'oily', 'sensitive'],
    concerns: ['acne'],
    ingredients: ['прогестерон'],
    price: 400,
    priceSegment: 'mass',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Гель с прогестероном для лечения акне',
    marketLinks: { apteka_ru: 'https://apteka.ru' },
  },
  {
    name: 'Циндол суспензия',
    brand: 'Russian',
    category: 'serum',
    step: 'treatment',
    skinTypes: ['oily'],
    concerns: ['acne'],
    ingredients: ['оксид цинка'],
    price: 150,
    priceSegment: 'mass',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Подсушивающая суспензия с оксидом цинка',
    marketLinks: { rigla: 'https://rigla.ru' },
  },
  {
    name: 'Комфодерм крем',
    brand: 'Russian',
    category: 'cream',
    step: 'treatment',
    skinTypes: ['sensitive'],
    concerns: ['acne'],
    ingredients: ['бетаметазон'],
    price: 300,
    priceSegment: 'mass',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Противовоспалительный крем',
    marketLinks: { ozon: 'https://ozon.ru' },
  },

  // ПОРЫ
  {
    name: 'Effaclar Gel очищающий',
    brand: 'La Roche-Posay',
    category: 'cleanser',
    step: 'cleansing',
    skinTypes: ['oily'],
    concerns: ['pores', 'acne'],
    ingredients: ['салициловая кислота'],
    price: 1000,
    priceSegment: 'mid',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Очищающий гель с салициловой кислотой для жирной кожи',
    marketLinks: { zdravcity: 'https://zdravcity.ru' },
  },
  {
    name: 'Sebium Gel',
    brand: 'Bioderma',
    category: 'cleanser',
    step: 'cleansing',
    skinTypes: ['combo'],
    concerns: ['pores'],
    ingredients: ['цинк', 'медь'],
    price: 1100,
    priceSegment: 'mid',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Очищающий гель для комбинированной кожи',
    marketLinks: { wildberries: 'https://wildberries.ru' },
  },
  {
    name: 'Cleanance Gel',
    brand: 'Avene',
    category: 'cleanser',
    step: 'cleansing',
    skinTypes: ['oily'],
    concerns: ['pores'],
    ingredients: ['термальная вода', 'цинк'],
    price: 900,
    priceSegment: 'mid',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Очищающий гель с термальной водой',
    marketLinks: { apteka_ru: 'https://apteka.ru' },
  },
  {
    name: 'Acne Cream',
    brand: 'Topicrem',
    category: 'cream',
    step: 'treatment',
    skinTypes: ['combo'],
    concerns: ['pores', 'acne'],
    ingredients: ['салициловая кислота'],
    price: 700,
    priceSegment: 'mid',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Крем для проблемной кожи',
    marketLinks: { rigla: 'https://rigla.ru' },
  },
  {
    name: 'Sensinol',
    brand: 'Noreva',
    category: 'serum',
    step: 'treatment',
    skinTypes: ['sensitive'],
    concerns: ['pores'],
    ingredients: ['ниацинамид'],
    price: 1200,
    priceSegment: 'mid',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Сыворотка с ниацинамидом для чувствительной кожи',
    marketLinks: { ozon: 'https://ozon.ru' },
  },
  {
    name: 'CapilarVit',
    brand: 'Dermedic',
    category: 'serum',
    step: 'treatment',
    skinTypes: ['oily'],
    concerns: ['pores'],
    ingredients: ['ниацинамид'],
    price: 800,
    priceSegment: 'mid',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Сыворотка для жирной кожи',
    marketLinks: { wildberries: 'https://wildberries.ru' },
  },

  // СУХОСТЬ
  {
    name: 'Lipikar Balm AP+ крем',
    brand: 'La Roche-Posay',
    category: 'cream',
    step: 'moisturizer',
    skinTypes: ['dry'],
    concerns: ['dryness'],
    ingredients: ['ниацинамид', 'масло ши'],
    price: 1400,
    priceSegment: 'mid',
    isFragranceFree: true,
    isNonComedogenic: false,
    descriptionUser: 'Интенсивно увлажняющий крем для сухой кожи',
    marketLinks: { zdravcity: 'https://zdravcity.ru' },
  },
  {
    name: 'Радевит мазь',
    brand: 'Russian',
    category: 'cream',
    step: 'moisturizer',
    skinTypes: ['dry', 'sensitive'],
    concerns: ['dryness'],
    ingredients: ['витамины A, D, E'],
    price: 300,
    priceSegment: 'mass',
    isFragranceFree: true,
    isNonComedogenic: false,
    descriptionUser: 'Регенерирующая мазь с витаминами',
    marketLinks: { apteka_ru: 'https://apteka.ru' },
  },
  {
    name: 'AtopiControl Balm',
    brand: 'Eucerin',
    category: 'cream',
    step: 'moisturizer',
    skinTypes: ['dry'],
    concerns: ['dryness'],
    ingredients: ['керамиды', 'липиды'],
    price: 1500,
    priceSegment: 'mid',
    isFragranceFree: true,
    isNonComedogenic: false,
    descriptionUser: 'Бальзам для атопической кожи',
    marketLinks: { rigla: 'https://rigla.ru' },
  },
  {
    name: 'Cicalfate крем',
    brand: 'Avene',
    category: 'cream',
    step: 'moisturizer',
    skinTypes: ['sensitive'],
    concerns: ['dryness'],
    ingredients: ['сульфат меди', 'сульфат цинка'],
    price: 1000,
    priceSegment: 'mid',
    isFragranceFree: true,
    isNonComedogenic: false,
    descriptionUser: 'Восстанавливающий крем для раздраженной кожи',
    marketLinks: { ozon: 'https://ozon.ru' },
  },
  {
    name: 'Atoderm Cream',
    brand: 'Bioderma',
    category: 'cream',
    step: 'moisturizer',
    skinTypes: ['dry'],
    concerns: ['dryness'],
    ingredients: ['глицерин', 'витамин E'],
    price: 1100,
    priceSegment: 'mid',
    isFragranceFree: true,
    isNonComedogenic: false,
    descriptionUser: 'Увлажняющий крем для сухой кожи',
    marketLinks: { wildberries: 'https://wildberries.ru' },
  },
  {
    name: 'Lipikar Lait',
    brand: 'Vichy',
    category: 'cream',
    step: 'moisturizer',
    skinTypes: ['combo'],
    concerns: ['dryness'],
    ingredients: ['ниацинамид'],
    price: 1300,
    priceSegment: 'mid',
    isFragranceFree: true,
    isNonComedogenic: false,
    descriptionUser: 'Увлажняющее молочко для комбинированной кожи',
    marketLinks: { apteka_ru: 'https://apteka.ru' },
  },
  {
    name: 'Hydracalm',
    brand: 'Institut Esthederm',
    category: 'serum',
    step: 'treatment',
    skinTypes: ['sensitive'],
    concerns: ['dryness'],
    ingredients: ['гиалуроновая кислота'],
    price: 2000,
    priceSegment: 'premium',
    isFragranceFree: true,
    isNonComedogenic: false,
    descriptionUser: 'Увлажняющая сыворотка для чувствительной кожи',
    marketLinks: { zdravcity: 'https://zdravcity.ru' },
  },

  // ПИГМЕНТАЦИЯ
  {
    name: 'Mela B3 сыворотка',
    brand: 'La Roche-Posay',
    category: 'serum',
    step: 'treatment',
    skinTypes: ['dry', 'normal', 'combo', 'oily', 'sensitive'],
    concerns: ['pigmentation'],
    ingredients: ['ниацинамид', 'ретинол'],
    price: 2000,
    priceSegment: 'premium',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Осветляющая сыворотка от пигментации',
    marketLinks: { rigla: 'https://rigla.ru' },
  },
  {
    name: 'Photoderm AR крем SPF50',
    brand: 'Bioderma',
    category: 'spf',
    step: 'spf',
    skinTypes: ['sensitive'],
    concerns: ['pigmentation'],
    ingredients: ['глюконат цинка'],
    price: 1600,
    priceSegment: 'mid',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Солнцезащитный крем для чувствительной кожи',
    marketLinks: { ozon: 'https://ozon.ru' },
  },
  {
    name: 'Idealia Pro',
    brand: 'Vichy',
    category: 'serum',
    step: 'treatment',
    skinTypes: ['dry'],
    concerns: ['pigmentation'],
    ingredients: ['ниацинамид'],
    price: 1800,
    priceSegment: 'mid',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Сыворотка для зрелой кожи',
    marketLinks: { apteka_ru: 'https://apteka.ru' },
  },
  {
    name: 'Anti-Pigment Serum',
    brand: 'Eucerin',
    category: 'serum',
    step: 'treatment',
    skinTypes: ['dry', 'normal', 'combo', 'oily'],
    concerns: ['pigmentation'],
    ingredients: ['транексамовая кислота'],
    price: 2200,
    priceSegment: 'premium',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Сыворотка против пигментации',
    marketLinks: { zdravcity: 'https://zdravcity.ru' },
  },
  {
    name: 'IKONOS Serum',
    brand: 'Noreva',
    category: 'serum',
    step: 'treatment',
    skinTypes: ['dry'],
    concerns: ['pigmentation'],
    ingredients: ['ретиналь'],
    price: 2500,
    priceSegment: 'premium',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Сыворотка с ретиналем для зрелой кожи',
    marketLinks: { rigla: 'https://rigla.ru' },
  },
  {
    name: 'Pigment Control',
    brand: 'Cytolife',
    category: 'serum',
    step: 'treatment',
    skinTypes: ['dry', 'normal', 'combo', 'oily', 'sensitive'],
    concerns: ['pigmentation'],
    ingredients: ['витамин C'],
    price: 1500,
    priceSegment: 'mid',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Сыворотка с витамином C для выравнивания тона',
    marketLinks: { ozon: 'https://ozon.ru' },
  },

  // МОРЩИНЫ
  {
    name: 'Retinol B3 сыворотка',
    brand: 'SkinCeuticals',
    category: 'serum',
    step: 'treatment',
    skinTypes: ['dry'],
    concerns: ['aging'],
    ingredients: ['ретинол', 'ниацинамид'],
    price: 5000,
    priceSegment: 'premium',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Антивозрастная сыворотка с ретинолом',
    marketLinks: { goldapple: 'https://goldapple.ru' },
  },
  {
    name: 'Адапален крем',
    brand: 'Generic',
    category: 'cream',
    step: 'treatment',
    skinTypes: ['combo'],
    concerns: ['aging', 'acne'],
    ingredients: ['адапален'],
    price: 700,
    priceSegment: 'mid',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Крем с адапаленом для комбинированной кожи',
    marketLinks: { apteka_ru: 'https://apteka.ru' },
  },
  {
    name: 'RetrinAL 0.05',
    brand: 'Avene',
    category: 'serum',
    step: 'treatment',
    skinTypes: ['dry'],
    concerns: ['aging'],
    ingredients: ['ретиналь'],
    price: 3000,
    priceSegment: 'premium',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Антивозрастная сыворотка с ретиналем',
    marketLinks: { wildberries: 'https://wildberries.ru' },
  },
  {
    name: 'Photoderm Max Aquafluide',
    brand: 'Bioderma',
    category: 'spf',
    step: 'spf',
    skinTypes: ['dry', 'normal', 'combo', 'oily', 'sensitive'],
    concerns: ['aging'],
    ingredients: ['антиоксиданты'],
    price: 1700,
    priceSegment: 'mid',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Солнцезащитный флюид с антиоксидантами',
    marketLinks: { zdravcity: 'https://zdravcity.ru' },
  },
  {
    name: 'Liftactiv Supreme',
    brand: 'Vichy',
    category: 'serum',
    step: 'treatment',
    skinTypes: ['dry'],
    concerns: ['aging'],
    ingredients: ['раминоза'],
    price: 2800,
    priceSegment: 'premium',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Антивозрастная сыворотка для зрелой кожи',
    marketLinks: { rigla: 'https://rigla.ru' },
  },
  {
    name: 'Hyaluron-Filler Serum',
    brand: 'Eucerin',
    category: 'serum',
    step: 'treatment',
    skinTypes: ['dry'],
    concerns: ['aging'],
    ingredients: ['гиалуроновая кислота'],
    price: 2000,
    priceSegment: 'premium',
    isFragranceFree: true,
    isNonComedogenic: false,
    descriptionUser: 'Увлажняющая сыворотка с гиалуроновой кислотой',
    marketLinks: { ozon: 'https://ozon.ru' },
  },
  {
    name: 'Retinol Cream',
    brand: 'PREMIUM',
    category: 'cream',
    step: 'treatment',
    skinTypes: ['combo'],
    concerns: ['aging'],
    ingredients: ['ретинол'],
    price: 1200,
    priceSegment: 'mid',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Антивозрастной крем с ретинолом',
    marketLinks: { wildberries: 'https://wildberries.ru' },
  },
  {
    name: 'Anti-Age Serum',
    brand: 'AADRE',
    category: 'serum',
    step: 'treatment',
    skinTypes: ['dry'],
    concerns: ['aging'],
    ingredients: ['пептиды'],
    price: 1800,
    priceSegment: 'mid',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Антивозрастная сыворотка с пептидами',
    marketLinks: { apteka_ru: 'https://apteka.ru' },
  },

  // SPF
  {
    name: 'UV Clear SPF46',
    brand: 'EltaMD',
    category: 'spf',
    step: 'spf',
    skinTypes: ['dry', 'normal', 'combo', 'oily', 'sensitive'],
    concerns: ['pigmentation', 'aging'],
    ingredients: ['ниацинамид'],
    price: 3500,
    priceSegment: 'premium',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Легкий солнцезащитный крем SPF46',
    marketLinks: { ozon: 'https://ozon.ru' },
  },
  {
    name: 'Anthelios SPF50',
    brand: 'La Roche-Posay',
    category: 'spf',
    step: 'spf',
    skinTypes: ['sensitive'],
    concerns: ['aging'],
    ingredients: ['термальная вода'],
    price: 1500,
    priceSegment: 'mid',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Солнцезащитный крем для чувствительной кожи',
    marketLinks: { rigla: 'https://rigla.ru' },
  },
  {
    name: 'Photoderm Spot SPF50',
    brand: 'Bioderma',
    category: 'spf',
    step: 'spf',
    skinTypes: ['sensitive'],
    concerns: ['pigmentation'],
    ingredients: ['ниацинамид'],
    price: 1400,
    priceSegment: 'mid',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Солнцезащитный крем против пигментации',
    marketLinks: { zdravcity: 'https://zdravcity.ru' },
  },
  {
    name: 'Very High Protection SPF50',
    brand: 'Avene',
    category: 'spf',
    step: 'spf',
    skinTypes: ['dry'],
    concerns: ['aging'],
    ingredients: ['термальная вода'],
    price: 1300,
    priceSegment: 'mid',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Высокозащитный солнцезащитный крем',
    marketLinks: { apteka_ru: 'https://apteka.ru' },
  },
  {
    name: 'Solaire Milk SPF50',
    brand: 'Topicrem',
    category: 'spf',
    step: 'spf',
    skinTypes: ['oily'],
    concerns: ['aging'],
    ingredients: ['витамин E'],
    price: 900,
    priceSegment: 'mid',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Легкое солнцезащитное молочко',
    marketLinks: { wildberries: 'https://wildberries.ru' },
  },
  {
    name: 'SPF30 (натуральное)',
    brand: 'Natura Siberica',
    category: 'spf',
    step: 'spf',
    skinTypes: ['dry', 'normal', 'combo', 'oily', 'sensitive'],
    concerns: ['aging'],
    ingredients: ['экстракты сибирских трав'],
    price: 600,
    priceSegment: 'mass',
    isFragranceFree: false,
    isNonComedogenic: true,
    descriptionUser: 'Натуральный солнцезащитный крем',
    marketLinks: { ozon: 'https://ozon.ru' },
  },

  // МАСКИ
  {
    name: 'Acne Clearing Mask',
    brand: 'Glytone',
    category: 'mask',
    step: 'treatment',
    skinTypes: ['oily'],
    concerns: ['acne'],
    ingredients: ['бензоилпероксид'],
    price: 2500,
    priceSegment: 'premium',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Маска для лечения акне',
    marketLinks: { goldapple: 'https://goldapple.ru' },
  },
  {
    name: 'Masque Vivant',
    brand: 'Biologique Recherche',
    category: 'mask',
    step: 'treatment',
    skinTypes: ['dry'],
    concerns: ['dryness'],
    ingredients: ['пробиотики'],
    price: 4000,
    priceSegment: 'premium',
    isFragranceFree: true,
    isNonComedogenic: false,
    descriptionUser: 'Омолаживающая маска с пробиотиками',
    marketLinks: {},
  },
  {
    name: 'Detox Mask',
    brand: 'G.Love',
    category: 'mask',
    step: 'treatment',
    skinTypes: ['oily', 'combo'],
    concerns: ['pores'],
    ingredients: ['уголь', 'кислоты'],
    price: 800,
    priceSegment: 'mid',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Детокс-маска для очищения пор',
    marketLinks: { wildberries: 'https://wildberries.ru' },
  },
  {
    name: 'Clay Mask',
    brand: 'SUPERBANKA',
    category: 'mask',
    step: 'treatment',
    skinTypes: ['oily'],
    concerns: ['pores', 'acne'],
    ingredients: ['глина', 'ниацинамид'],
    price: 500,
    priceSegment: 'mass',
    isFragranceFree: true,
    isNonComedogenic: true,
    descriptionUser: 'Глиняная маска для жирной кожи',
    marketLinks: { ozon: 'https://ozon.ru' },
  },
] as const;

async function seedProductsExtended() {
  console.log('🌱 Seeding extended products database...');

  // Создаем бренды
  const brandMap = new Map<string, number>();
  
  for (const brandData of BRANDS) {
    const brand = await prisma.brand.upsert({
      where: { name: brandData.name },
      update: { country: brandData.country },
      create: {
        name: brandData.name,
        country: brandData.country,
        isActive: true,
      },
    });
    brandMap.set(brandData.name, brand.id);
    console.log(`  ✅ Brand: ${brandData.name}`);
  }

  // Создаем продукты
  let createdCount = 0;
  let updatedCount = 0;

  for (const productData of PRODUCTS) {
    const brandId = brandMap.get(productData.brand);
    if (!brandId) {
      console.error(`  ❌ Brand not found: ${productData.brand}`);
      continue;
    }

    const existing = await prisma.product.findFirst({
      where: {
        brandId,
        name: productData.name,
      },
    });

    const productPayload = {
      brandId,
      name: productData.name,
      line: null,
      category: productData.category,
      step: productData.step,
      skinTypes: productData.skinTypes,
      concerns: productData.concerns,
      isFragranceFree: productData.isFragranceFree,
      isNonComedogenic: productData.isNonComedogenic,
      priceSegment: productData.priceSegment,
      price: productData.price,
      descriptionUser: productData.descriptionUser,
      marketLinks: productData.marketLinks as any,
      status: 'published' as const,
    };

    if (existing) {
      await prisma.product.update({
        where: { id: existing.id },
        data: productPayload,
      });
      updatedCount++;
      console.log(`  🔄 Updated: ${productData.brand} - ${productData.name}`);
    } else {
      await prisma.product.create({
        data: productPayload,
      });
      createdCount++;
      console.log(`  ✅ Created: ${productData.brand} - ${productData.name}`);
    }
  }

  console.log(`\n✅ Products seeding completed!`);
  console.log(`   Created: ${createdCount}`);
  console.log(`   Updated: ${updatedCount}`);
  console.log(`   Total: ${PRODUCTS.length}`);
}

seedProductsExtended()
  .catch((e) => {
    console.error('❌ Error seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

